/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AdminApiKeys: typeof import('./components/admin/AdminApiKeys.vue')['default']
    AdminClaimTable: typeof import('./components/admin/AdminClaimTable.vue')['default']
    AdminContentDrawer: typeof import('./components/admin/AdminContentDrawer.vue')['default']
    AdminContentTable: typeof import('./components/admin/AdminContentTable.vue')['default']
    AdminPollPanel: typeof import('./components/admin/AdminPollPanel.vue')['default']
    AdminReportTable: typeof import('./components/admin/AdminReportTable.vue')['default']
    AdminThemeSettings: typeof import('./components/admin/AdminThemeSettings.vue')['default']
    AdminUploadPanel: typeof import('./components/admin/AdminUploadPanel.vue')['default']
    AdminUserTable: typeof import('./components/admin/AdminUserTable.vue')['default']
    CommentItem: typeof import('./components/CommentItem.vue')['default']
    ConfirmDialog: typeof import('./components/ConfirmDialog.vue')['default']
    ContentTypeBadge: typeof import('./components/ContentTypeBadge.vue')['default']
    ErrorBoundary: typeof import('./components/ErrorBoundary.vue')['default']
    HomeContentCard: typeof import('./components/HomeContentCard.vue')['default']
    HomePagination: typeof import('./components/HomePagination.vue')['default']
    MarkdownModal: typeof import('./components/MarkdownModal.vue')['default']
    MarkdownToolbar: typeof import('./components/MarkdownToolbar.vue')['default']
    MessageBanner: typeof import('./components/MessageBanner.vue')['default']
    ModalBase: typeof import('./components/ModalBase.vue')['default']
    PollComponent: typeof import('./components/PollComponent.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagCloud: typeof import('./components/admin/TagCloud.vue')['default']
    ThemeSwitcher: typeof import('./components/ThemeSwitcher.vue')['default']
  }
}
